"""empty message

Revision ID: 0fd837792538
Revises: e672e9391af5
Create Date: 2024-07-30 15:10:50.757141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fd837792538'
down_revision = 'e672e9391af5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Book', schema=None) as batch_op:
        batch_op.drop_column('price')

    with op.batch_alter_table('Coffee', schema=None) as batch_op:
        batch_op.drop_column('price')

    with op.batch_alter_table('Videogame', schema=None) as batch_op:
        batch_op.drop_column('price')

    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart_items', schema=None) as batch_op:
        batch_op.drop_column('price')

    with op.batch_alter_table('Videogame', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.FLOAT(), nullable=False))

    with op.batch_alter_table('Coffee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.FLOAT(), nullable=False))

    with op.batch_alter_table('Book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.FLOAT(), nullable=False))

    # ### end Alembic commands ###
