"""correct one-to-one relationship between cart and user

Revision ID: c480e49f3ffd
Revises: 
Create Date: 2024-07-22 14:33:37.911400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c480e49f3ffd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Coffee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coffeeName', sa.Text(), nullable=False),
    sa.Column('favCount', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['Cart.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('coffee')
    with op.batch_alter_table('Book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cart_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'Cart', ['cart_id'], ['id'])

    with op.batch_alter_table('Cart', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('Videogame', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cart_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'Cart', ['cart_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Videogame', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cart_id')

    with op.batch_alter_table('Cart', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('Book', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cart_id')

    op.create_table('coffee',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('coffeeName', sa.TEXT(), nullable=False),
    sa.Column('favCount', sa.INTEGER(), nullable=True),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('Coffee')
    # ### end Alembic commands ###
